### ISSUE TITLE
Error: node-gyp failed to rebuild blake2 - Could not find any Visual Studio installation to use

### ISSUE THREAD

**Issue by roberto-sanfelice** [vrza/node-blake2#28]
I'm trying to run `.\node_modules\.bin\electron-rebuild.cmd`
but this is what I get:

```
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\user\Desktop\app\node_modules\blake2'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use



Error: node-gyp failed to rebuild 'C:\Users\user\Desktop\app\node_modules\blake2'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use


    at NodeGyp.rebuildModule (C:\Users\user\Desktop\app\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:109:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (C:\Users\user\Desktop\app\node_modules\electron-rebuild\lib\src\module-rebuilder.js:94:9)
    at async Rebuilder.rebuildModuleAt (C:\Users\user\Desktop\app\node_modules\electron-rebuild\lib\src\rebuild.js:226:9)
    at async Rebuilder.rebuild (C:\Users\user\Desktop\app\node_modules\electron-rebuild\lib\src\rebuild.js:184:17)
    at async C:\Users\user\Desktop\app\node_modules\electron-rebuild\lib\src\cli.js:154:9
```

I've been trying to fix this since days. Everything is correctly installed on system, from visual studio to c++ developers tools and python 2.7. Can't figure out how to make it work.

**Comment by vrza** [comment]
Hi @roberto-sanfelice . On first glance this seems to be an issue with your setup, rather than a bug in node-blake2. Can you try following some of the guides on this thread https://github.com/nodejs/node-gyp/issues/2203 and see if it helps? Running the npm command with `--loglevel silly` might help pinpoint the issue.

**Comment by vrza** [comment]
@roberto-sanfelice I just confirmed everything working fine in a Windows 11 VM, as described in the README:

- install Node.js using Windows installer from nodejs.org
- make sure to check box "install additional tools"
